services:
  # Container for the ASP.NET app
  my-aspnet-app:
    image: aspnetapp-mongodb:latest
    stdin_open: true
    tty: true
    ports:
      - ${ASPNETCORE_HOST_PORT}:${ASPNETCORE_HTTP_PORTS}
    environment:
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - MONGODB_URI=mongodb://{username}:{password}@mongodb:${MONGODB_PORT}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PW=${MONGODB_PW}

  # MongoDB Server
  mongodb:
    image: mongo
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ${MONGODB_HOST_DIRECTORY}:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PW}
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DATABASE}
